using System;
Console.WriteLine("=== 문자열 처리 파이프라인 ===");
Action<string> PrintOriginal = (s) => Console.WriteLine("원본: Hello World");
Action<string> PrintUpper = (s) => Console.WriteLine($"대문자: {s.ToUpper()}");
Action<string> PrintLower = (s) => Console.WriteLine($"소문자: {s.ToLower()}");
Action<string> PrintLength = (s) => Console.WriteLine($"길이: {s.Length}");
Action<string> PrintText = PrintOriginal;
Console.WriteLine("=== 문자열 처리 파이프라인 ===");
Console.WriteLine();
Console.WriteLine("--- 단계 1: 원본 출력만 ---");
PrintText("");
Console.WriteLine();
Console.WriteLine("--- 단계 2: 대문자 추가 ---");
PrintText += PrintUpper;
PrintText("Hello World");
Console.WriteLine();
Console.WriteLine("--- 단계 3: 소문자, 길이 추가 ---");
PrintText += PrintLower;
PrintText += PrintLength;
PrintText("Hello World");
Console.WriteLine();
Console.WriteLine("--- 단계 4: 대문자 제거 ---");
PrintText -= PrintUpper;
PrintText("Hello World");
